apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sDeniesPrivileged
metadata:
  name: no-privileged-containers
spec:
  enforcementAction: deny
  match:
    scope: Namespaced
    kinds:
    - apiGroups:
      - ""
      kinds:
      - Pod
    excludedNamespaces:
    - kube-system
    - kube-public
    - kube-node-lease
    - gatekeeper-system
