apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"app":"debug-test"},"name":"failing-app","namespace":"observability-health"},"spec":{"containers":[{"image":"nginx:alpine","livenessProbe":{"failureThreshold":2,"httpGet":{"path":"/nonexistent-path","port":80},"initialDelaySeconds":5,"periodSeconds":5,"timeoutSeconds":2},"name":"failing-container","ports":[{"containerPort":80}],"readinessProbe":{"failureThreshold":2,"httpGet":{"path":"/also-nonexistent","port":80},"initialDelaySeconds":2,"periodSeconds":3,"timeoutSeconds":2},"resources":{"limits":{"cpu":"200m","memory":"128Mi"},"requests":{"cpu":"25m","memory":"32Mi"}}}]}}
  creationTimestamp: "2026-09-18T16:54:42Z"
  generation: 1
  labels:
    app: debug-test
  name: failing-app
  namespace: observability-health
  resourceVersion: "844"
  uid: 8e95c2e0-65b2-4f22-b0e1-2999be59c367
spec:
  containers:
  - image: nginx:alpine
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 2
      httpGet:
        path: /nonexistent-path
        port: 80
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 2
    name: failing-container
    ports:
    - containerPort: 80
      protocol: TCP
    readinessProbe:
      failureThreshold: 2
      httpGet:
        path: /also-nonexistent
        port: 80
        scheme: HTTP
      initialDelaySeconds: 2
      periodSeconds: 3
      successThreshold: 1
      timeoutSeconds: 2
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 25m
        memory: 32Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-n54x9
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-n54x9
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  allocatedResources:
    cpu: 25m
    memory: 32Mi
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-09-18T16:54:42Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-09-18T16:54:42Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-09-18T16:54:42Z"
    message: 'containers with unready status: [failing-container]'
    observedGeneration: 1
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-09-18T16:54:42Z"
    message: 'containers with unready status: [failing-container]'
    observedGeneration: 1
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-09-18T16:54:42Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - allocatedResources:
      cpu: 25m
      memory: 32Mi
    containerID: containerd://5635cea7e1f220877067d8c4a85d9e93528d67bf8af4461075000c20aaf01cb5
    image: docker.io/library/nginx:alpine
    imageID: docker.io/library/nginx@sha256:62ff2089abf5a9ed33bd232895bef5e22f7bb4b200675cec49a5ebc48e3d4ac8
    lastState:
      terminated:
        containerID: containerd://199970ddd05ce16f84049318418f715b9f58388afb4d5cca26897bc76eca78b9
        exitCode: 0
        finishedAt: "2026-09-18T16:54:52Z"
        reason: Completed
        startedAt: "2026-09-18T16:54:42Z"
    name: failing-container
    ready: false
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 25m
        memory: 32Mi
    restartCount: 1
    started: true
    state:
      running:
        startedAt: "2026-09-18T16:54:52Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 6
        - 10
        - 11
        - 20
        - 26
        - 27
        uid: 0
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-n54x9
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.49.2
  hostIPs:
  - ip: 192.168.49.2
  observedGeneration: 1
  phase: Running
  podIP: 10.244.0.9
  podIPs:
  - ip: 10.244.0.9
  qosClass: Burstable
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      memory: 32Mi
  startTime: "2026-09-18T16:54:42Z"
