apiVersion: v1
items:
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.244.0.21
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: minikube
    targetRef:
      kind: Pod
      name: sample-app-v3-74c96d599b-bn9cm
      namespace: deployment-strategies
      uid: effef146-537f-494d-9437-0c36590d9e17
  - addresses:
    - 10.244.0.22
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: minikube
    targetRef:
      kind: Pod
      name: sample-app-v3-74c96d599b-6pvj8
      namespace: deployment-strategies
      uid: 86b38598-c175-4bdc-973e-c579a9d12519
  - addresses:
    - 10.244.0.23
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: minikube
    targetRef:
      kind: Pod
      name: sample-app-v3-74c96d599b-xbvzk
      namespace: deployment-strategies
      uid: 93eeb3ef-c9f5-4a05-89ca-31b78af98910
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-09-18T16:11:21Z"
    creationTimestamp: "2026-09-18T16:04:57Z"
    generateName: sample-app-service-
    generation: 62
    labels:
      app: sample-app
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      kubernetes.io/service-name: sample-app-service
    name: sample-app-service-5q9cc
    namespace: deployment-strategies
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: sample-app-service
      uid: f21dedf0-ca57-490d-a934-6c83cae146ac
    resourceVersion: "1618"
    uid: c407dacd-34f8-43f3-8ea5-c9f14020d2a2
  ports:
  - name: http
    port: 80
    protocol: TCP
kind: List
metadata:
  resourceVersion: ""
