apiVersion: v1
kind: Pod
metadata:
  name: problematic-pod
  labels:
    app: problematic-security
spec:
  restartPolicy: Never

  securityContext:
    runAsNonRoot: true
    runAsUser: 0

  containers:
    - name: problem-container
      image: nginx:1.29-alpine

      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false

        capabilities:
          drop:
            - ALL

        seccompProfile:
          type: RuntimeDefault
