apiVersion: v1
kind: PersistentVolume
metadata:
  name: secondary-pv
  labels:
    storage-role: secondary
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /tmp/persistent-data-secondary
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
