apiVersion: v1
kind: PersistentVolume
metadata:
  name: primary-pv
  labels:
    storage-role: primary
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /tmp/persistent-data-primary
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
