apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: primary-pvc
  namespace: persistent-storage
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
