apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: network-segmentation
  labels:
    app: frontend
    tier: web
spec:
  containers:
    - name: frontend
      image: nginx:alpine
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "32Mi"
          cpu: "25m"
        limits:
          memory: "128Mi"
          cpu: "100m"
