apiVersion: v1
kind: Pod
metadata:
  name: readonly-pod
  namespace: testing
  labels:
    access-profile: readonly
spec:
  serviceAccountName: readonly-user
  automountServiceAccountToken: true
  containers:
    - name: kubectl
      image: bitnami/kubectl:latest
      command:
        - sh
        - -c
        - sleep 3600
      resources:
        requests:
          cpu: 25m
          memory: 32Mi
        limits:
          cpu: 100m
          memory: 128Mi
  restartPolicy: Never
