FROM debian:11-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      curl \
      wget \
      openssl \
      python3 \
      ca-certificates && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY app.py /app/app.py

CMD ["python3", "/app/app.py"]
