apiVersion: v1
kind: Pod
metadata:
  name: signed-app
  namespace: supply-chain-demo
spec:
  containers:
    - name: app
      image: localhost:5001/secure-app@sha256:<IMAGE_DIGEST>
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 101
        capabilities:
          drop:
            - ALL
  restartPolicy: Never
