apiVersion: apps/v1
kind: Deployment
metadata:
  name: unsigned-app
  namespace: supply-chain-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unsigned-app
  template:
    metadata:
      labels:
        app: unsigned-app
    spec:
      containers:
        - name: app
          image: localhost:5001/unsigned-nginx@sha256:<IMAGE_DIGEST>
          imagePullPolicy: Always
