apiVersion: policies.kyverno.io/v1
kind: ImageValidatingPolicy
metadata:
  name: verify-local-supply-chain-images
spec:
  failurePolicy: Fail

  validationActions:
    - Deny

  webhookConfiguration:
    timeoutSeconds: 30

  evaluation:
    background:
      enabled: false

  matchConstraints:
    resourceRules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods

  matchConditions:
    - name: supply-chain-namespace
      expression: >-
        object.metadata.namespace == "supply-chain-demo"

  matchImageReferences:
    - glob: "localhost:5001/*"

  credentials:
    allowInsecureRegistry: true

  attestors:
    - name: cosign
      cosign:
        key:
          data: |
      -----BEGIN PUBLIC KEY-----
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE37rIdr99fA8Ymo4TFrE/kJPPrKvr
      Y8Z9fPHdtRs39L7NfeZoIlmZV7T2nvKXrXkwRH0ILALM2jqURdanxMKY1g==
      -----END PUBLIC KEY-----

  validationConfigurations:
    mutateDigest: false
    required: true
    verifyDigest: true

  validations:
    - expression: >-
        images.containers.map(
          image,
          verifyImageSignatures(image, [attestors.cosign])
        ).all(result, result > 0)
      message: >-
        container image must have a valid Cosign signature from the trusted signing key
