apiVersion: v1
kind: LimitRange
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"LimitRange","metadata":{"annotations":{},"name":"default-limits","namespace":"resource-governance"},"spec":{"limits":[{"default":{"cpu":"200m","memory":"128Mi"},"defaultRequest":{"cpu":"100m","memory":"64Mi"},"type":"Container"}]}}
  creationTimestamp: "2026-09-18T18:50:58Z"
  name: default-limits
  namespace: resource-governance
  resourceVersion: "992"
  uid: d1b8e9d7-ad5a-4ae2-8b57-bcab17503ef0
spec:
  limits:
  - default:
      cpu: 200m
      memory: 128Mi
    defaultRequest:
      cpu: 100m
      memory: 64Mi
    type: Container
