apiVersion: v1
kind: Pod
metadata:
  name: network-test
  namespace: runtime-debugging
spec:
  containers:
    - name: minimal-network-app
      image: busybox:1.37
      command: ["/bin/sh", "-c", "sleep 3600"]
