apiVersion: v1
kind: Pod
metadata:
  name: resource-issue-pod
  namespace: runtime-debugging
spec:
  containers:
    - name: app
      image: nginx:alpine
      resources:
        requests:
          memory: "10Gi"
          cpu: "8"
        limits:
          memory: "10Gi"
          cpu: "8"
