USER-SUPPLIED VALUES:
extraEnvVars:
- name: APACHE_SERVER_NAME
  value: my-custom-server
- name: ENVIRONMENT
  value: development
global:
  security:
    allowInsecureImages: true
image:
  registry: docker.io
  repository: bitnamilegacy/apache
  tag: 2.4.65-debian-12-r2
replicaCount: 3
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
service:
  type: ClusterIP
