apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-pvc
  labels:
    app: dynamic-storage-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: fast-storage
