apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: database-role
  namespace: access-control
  labels:
    app.kubernetes.io/name: database
    security.kubernetes.io/purpose: least-privilege
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get

  - apiGroups: [""]
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch

  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - watch
