apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-service-account
  namespace: access-control
  labels:
    app.kubernetes.io/name: monitoring
    security.kubernetes.io/purpose: cluster-read-only
automountServiceAccountToken: false
