apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: production

namePrefix: production-

replicas:
- name: cicd-app
  count: 3

patches:
- target:
    kind: Deployment
    name: cicd-app
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "production"
