apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  template:
    spec:
      containers:
        - name: webapp
          image: nginx:1.28-alpine
          env:
            - name: ENVIRONMENT
              value: "development"
            - name: DEBUG
              value: "true"
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
