apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-app
  labels:
    app: database
spec:
  replicas: 2
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: tier
                    operator: In
                    values:
                      - database
                  - key: disk
                    operator: In
                    values:
                      - ssd
      containers:
        - name: database
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 32Mi
              cpu: 20m
            limits:
              memory: 64Mi
              cpu: 100m
