kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
  - role: control-plane

  - role: worker
    labels:
      scheduling.demo/role: worker-a

  - role: worker
    labels:
      scheduling.demo/role: worker-b
