apiVersion: flowcontrol.apiserver.k8s.io/v1
kind: FlowSchema
metadata:
  name: limited-user-flow
spec:
  matchingPrecedence: 1000

  priorityLevelConfiguration:
    name: limited-priority

  distinguisherMethod:
    type: ByUser

  rules:
  - subjects:
    - kind: ServiceAccount
      serviceAccount:
        name: limited-user
        namespace: security-test

    resourceRules:
    - verbs:
      - "*"

      apiGroups:
      - "*"

      resources:
      - "*"

      namespaces:
      - "*"

      clusterScope: true
