apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-app
  namespace: development
  labels:
    app: secure-app
spec:
  replicas: 2

  selector:
    matchLabels:
      app: secure-app

  template:
    metadata:
      labels:
        app: secure-app

    spec:
      serviceAccountName: dev-user
      automountServiceAccountToken: false

      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: secure-app
          image: nginxinc/nginx-unprivileged:alpine

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true

            capabilities:
              drop:
                - ALL

          resources:
            requests:
              cpu: 50m
              memory: 64Mi

            limits:
              cpu: 100m
              memory: 128Mi

          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx

            - name: nginx-run
              mountPath: /var/run

            - name: tmp
              mountPath: /tmp

      volumes:
        - name: nginx-cache
          emptyDir: {}

        - name: nginx-run
          emptyDir: {}

        - name: tmp
          emptyDir: {}
