apiVersion: v1
kind: Pod
metadata:
  name: secure-policy-test
  namespace: development
spec:
  containers:
    - name: nginx
      image: nginxinc/nginx-unprivileged:alpine
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
