apiVersion: v1
kind: Pod
metadata:
  name: custom-sa-pod
  namespace: secure-app
spec:
  serviceAccountName: app-service-account
  restartPolicy: Never
  containers:
    - name: api-test
      image: curlimages/curl:8.10.1
      command:
        - sh
        - -c
        - sleep 3600
