apiVersion: v1
kind: Pod
metadata:
  name: baseline-style-app
  namespace: restricted-test
spec:
  containers:
    - name: app
      image: nginx:1.28-alpine
      command:
        - sh
        - -c
        - sleep 3600
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 101
        capabilities:
          drop:
            - ALL
  restartPolicy: Never
