apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"hardened-web","namespace":"kernel-hardening"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":8080}],"selector":{"app":"hardened-web"},"type":"ClusterIP"}}
  creationTimestamp: "2026-10-09T14:47:47Z"
  name: hardened-web
  namespace: kernel-hardening
  resourceVersion: "633"
  uid: 955e09f9-2481-4577-bdef-f97c71aeb501
spec:
  clusterIP: 10.43.67.116
  clusterIPs:
  - 10.43.67.116
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hardened-web
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
