apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"app":"debug-demo-working"},"name":"working-app","namespace":"runtime-debugging"},"spec":{"containers":[{"env":[{"name":"SERVER_NAME","value":"debug-server"}],"image":"nginx:alpine","name":"web-server","ports":[{"containerPort":80}],"resources":{"limits":{"cpu":"200m","memory":"128Mi"},"requests":{"cpu":"25m","memory":"32Mi"}},"volumeMounts":[{"mountPath":"/var/app-data","name":"app-data"}]}],"restartPolicy":"Always","volumes":[{"emptyDir":{},"name":"app-data"}]}}
  creationTimestamp: "2026-09-18T17:07:58Z"
  generation: 1
  labels:
    app: debug-demo-working
  name: working-app
  namespace: runtime-debugging
  resourceVersion: "536"
  uid: 5bb9454f-0c5a-4006-8e9d-4770fffeb0a8
spec:
  containers:
  - env:
    - name: SERVER_NAME
      value: debug-server
    image: nginx:alpine
    imagePullPolicy: IfNotPresent
    name: web-server
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 25m
        memory: 32Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/app-data
      name: app-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-dfxx4
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: app-data
  - name: kube-api-access-dfxx4
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  allocatedResources:
    cpu: 25m
    memory: 32Mi
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-09-18T17:07:59Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-09-18T17:07:58Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-09-18T17:08:02Z"
    observedGeneration: 1
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-09-18T17:08:02Z"
    observedGeneration: 1
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-09-18T17:07:58Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - allocatedResources:
      cpu: 25m
      memory: 32Mi
    containerID: containerd://e237c0ac774cb2f1349faf3871b580e8197ad30004b94e5164b01e7d2283fa28
    image: docker.io/library/nginx:alpine
    imageID: docker.io/library/nginx@sha256:62ff2089abf5a9ed33bd232895bef5e22f7bb4b200675cec49a5ebc48e3d4ac8
    lastState: {}
    name: web-server
    ready: true
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 25m
        memory: 32Mi
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-09-18T17:08:02Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 6
        - 10
        - 11
        - 20
        - 26
        - 27
        uid: 0
    volumeMounts:
    - mountPath: /var/app-data
      name: app-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-dfxx4
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.49.2
  hostIPs:
  - ip: 192.168.49.2
  observedGeneration: 1
  phase: Running
  podIP: 10.244.0.3
  podIPs:
  - ip: 10.244.0.3
  qosClass: Burstable
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 25m
      memory: 32Mi
  startTime: "2026-09-18T17:07:58Z"
