apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: security-lab
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list

  - apiGroups: [""]
    resources:
      - pods/log
    verbs:
      - get
