apiVersion: v1
kind: Pod
metadata:
  name: restricted-negative-test
  namespace: restricted-demo
spec:
  containers:
    - name: nginx
      image: nginx:stable-alpine
      securityContext:
        allowPrivilegeEscalation: false
