apiVersion: v1
kind: Pod
metadata:
  name: hardened-client
  namespace: kernel-hardening
spec:
  restartPolicy: Never
  automountServiceAccountToken: false
  containers:
    - name: client
      image: busybox:1.36
      command:
        - /bin/sh
        - -c
        - |
          sleep 3600
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 10002
        runAsGroup: 10002
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop:
            - ALL
